In [155]:
import numpy as np
import pandas as pd
from pivottablejs import pivot_ui
import matplotlib.pyplot as plt
import matplotlib
from sklearn import preprocessing 
matplotlib.style.use('ggplot')
%matplotlib inline

from pylab import rcParams
rcParams['figure.figsize'] = 20, 20
rcParams.update({'font.size': 30})
rcParams.update({'figure.autolayout': True})

data = pd.read_csv("cleanSet.csv")

(1, 100)

In [68]:
from sklearn import tree
import numpy as np

x = np.matrix(data['population'])
y = np.matrix(data['Cases'])


training_x = x[0,:261].T
traning_y = y[0,:261].T

test_x = x[0,261:].T
test_y = y[0,261:].T



classifier = tree.DecisionTreeClassifier()
classifier.fit(training_x,traning_y)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [77]:
print training_x.shape
print test_x.shape

(261, 1)
(29, 1)


In [92]:
error = test_y.T -np.matrix(classifier.predict(test_x))
print np.sqrt(np.square(error)).sum()


27.0


In [140]:
from sklearn import tree
import numpy as np

x = np.matrix(data.drop('Cases',axis=1).dropna())
y = np.matrix(data['Cases'])


training_x = x[:261,:]
training_y = y[0,:261].T

test_x = x[261:,:]
test_y = y[0,261:].T



classifier = tree.DecisionTreeClassifier()
classifier.fit(training_x,training_y)

print classifier.predict(test_x)
print test_y.T[0,:]

[ 0  2  5  0  0  0  0  0  0  0  1  0  0  0  0  0  2  0  0  0 11  0  0  0  0
  0  0  0  0]
[[0 0 1 1 0 0 1 0 0 0 0 0 0 3 0 0 0 0 1 0 7 0 0 1 0 0 0 0 0]]


In [128]:
print training_x.shape
print training_y.shape

(261, 15)
(261, 1)


In [194]:
def f(x):
    if x > 0:
        return 1
    else:
        return 0

from sklearn import tree
import numpy as np

x = np.matrix(data.drop('Cases',axis=1).dropna())
y = np.matrix(data['Cases'].apply(f))

training_x = x[:261,:]
training_y = y[0,:261].T

test_x = x[261:,:]
test_y = y[0,261:].T



classifier = tree.DecisionTreeClassifier(min_samples_split=100)
classifier.fit(training_x,training_y)

print classifier.predict(test_x)
print test_y.T[0,:]
    

error = test_y.T[0,:] - classifier.predict(test_x)
print np.sqrt(np.square(error)).sum()


[0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0]
[[0 0 1 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0]]
6.0


In [182]:
def f(x):
    if x > 0:
        return 1
    else:
        return 0

from sklearn.ensemble import RandomForestClassifier
import numpy as np

x = np.matrix(data.drop('Cases',axis=1).dropna())
y = np.matrix(data['Cases'].apply(f))

training_x = x[:261,:]
training_y = y[0,:261].T

test_x = x[261:,:]
test_y = y[0,261:].T



classifier = RandomForestClassifier(n_estimators=100)
classifier.fit(training_x,training_y)

print classifier.predict(test_x)
print test_y.T[0,:]
    

error = test_y.T[0,:] - classifier.predict(test_x)
print 1- np.sqrt(np.square(error)).sum()/len(test_x)


/home/adam/anaconda2/envs/deeplearning/lib/python2.7/site-packages/ipykernel/__main__.py:22: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().


[0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0]
[[0 0 1 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0]]
0.793103448276


In [197]:
from sklearn.linear_model import LogisticRegression
##Regression
def f(x):
    if x > 0:
        return 1
    else:
        return 0
import numpy as np

x = np.matrix(data.drop('Cases',axis=1).dropna())
y = np.matrix(data['Cases'].apply(f))

count = 250

training_x = x[:count,:]
training_y = y[0,:count].T

test_x = x[count:,:]
test_y = y[0,count:].T



classifier = LogisticRegression()
classifier.fit(training_x,training_y)

print classifier.predict(test_x)
print test_y.T[0,:]


error = test_y.T[0,:] - classifier.predict(test_x)
print 1- np.sqrt(np.square(error)).sum()/len(test_x)


[0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0
 0 0 0]
[[0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0
  0 0 0]]
0.85


/home/adam/anaconda2/envs/deeplearning/lib/python2.7/site-packages/sklearn/utils/validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [221]:
case_popu = np.matrix(data[['Cases','population']])



2436

In [298]:
#Number of fire per 1000 


from sklearn.linear_model import LinearRegression
##Regression
def f(x):
    if x > 0:
        return 1
    else:
        return 0
import numpy as np

x = np.matrix(data.drop(['Cases','population'],axis=1).dropna())
# y = np.matrix((data['Cases'] / data['population']) *1e3)
y = np.matrix(data['Cases'])

count = 200

training_x = x[:count,:]
training_y = y[0,:count].T


test_x = x[count:,:]
test_y = y[0,count:].T




classifier = LinearRegression()
classifier.fit(training_x,training_y)


error = test_y[:,0] - classifier.predict(test_x)
# error = test_y[0,:] - test_y[0,:]
print ( np.sqrt(np.square(error)).sum()/len(test_y)), "Mean squared error"
print "Error" , error.shape


0.850826481239 Mean squared error
Error (90, 1)


In [230]:
y = np.matrix((data['Cases'] / data['population']) *1e3)

In [268]:
test_y[:,0].shape

(90, 1)

In [302]:
print classifier.predict(tex)[0:5]
print test_y[0:5]


[[ 0.75474704]
 [ 0.78911675]
 [ 0.28713143]
 [ 0.42309399]
 [ 3.4495029 ]]
[[0]
 [2]
 [0]
 [0]
 [2]]


In [245]:
classifier.predict(test_x).shape

(40, 1)

In [251]:
classifier.coef_

array([[  6.27201309e-08,   3.98229128e-04,   1.23525867e-03,
         -2.14545824e-03,   3.47648762e-06,   5.98035725e-04,
         -9.02876144e-05,  -3.60056101e-07,   2.58358341e-04,
          6.09453252e-04,   1.95097963e-04,  -1.02147001e-04,
         -1.61910596e-08,  -1.41158055e-04,   1.64828352e-05]])

In [283]:
data['population']

0       28074
1       38619
2       19280
3        6375
4       13493
5        2980
6        6471
7       25817
8       11096
9       21582
10       9550
11       7160
12       2436
13      14801
14      27838
15       8562
16      26141
17      10619
18      50023
19     105995
20      87580
21       5278
22      12336
23       6559
24      17114
25      14275
26       4740
27      32222
28       9500
29       2757
        ...  
260     33155
261     35867
262    142131
263     85822
264     11065
265      3617
266     28623
267     15759
268      7096
269      9132
270      8168
271     39866
272     12229
273      9548
274     10420
275      9953
276      2875
277     14927
278     11460
279     12574
280      5174
281    140599
282      9653
283     54986
284     59956
285     40495
286     21352
287     13687
288      3436
289      4709
Name: population, dtype: int64