In [1]:
import numpy as np
import pandas as pd
from pivottablejs import pivot_ui
import matplotlib.pyplot as plt
import matplotlib
from sklearn import preprocessing 
matplotlib.style.use('ggplot')
%matplotlib inline

from pylab import rcParams
rcParams['figure.figsize'] = 20, 20
rcParams.update({'font.size': 30})
rcParams.update({'figure.autolayout': True})

data = pd.read_csv("cleanSet.csv")

In [2]:
from sklearn import tree
import numpy as np

x = np.matrix(data['population'])
y = np.matrix(data['Cases'])


training_x = x[0,:261].T
traning_y = y[0,:261].T

test_x = x[0,261:].T
test_y = y[0,261:].T



classifier = tree.DecisionTreeClassifier()
classifier.fit(training_x,traning_y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [3]:
error = test_y.T -np.matrix(classifier.predict(test_x))

print np.sqrt(np.square(error)).sum()


27.0


In [4]:
from sklearn import tree
import numpy as np

x = np.matrix(data.drop('Cases',axis=1).dropna())
y = np.matrix(data['Cases'])


training_x = x[:261,:]
training_y = y[0,:261].T

test_x = x[261:,:]
test_y = y[0,261:].T



classifier = tree.DecisionTreeClassifier()
classifier.fit(training_x,training_y)

print classifier.predict(test_x)
print test_y.T[0,:]
#The tree classifier is not performing that well.

[0 2 5 0 0 0 1 0 0 0 1 0 0 0 0 0 2 0 0 0 7 0 1 0 0 0 0 0 0]
[[0 0 1 1 0 0 1 0 0 0 0 0 0 3 0 0 0 0 1 0 7 0 0 1 0 0 0 0 0]]


In [5]:
print training_x.shape
print training_y.shape

(261, 15)
(261, 1)


In [6]:
def f(x):
    if x > 0:
        return 1
    else:
        return 0

from sklearn import tree
import numpy as np

x = np.matrix(data.drop('Cases',axis=1).dropna())
y = np.matrix(data['Cases'].apply(f))

training_x = x[:261,:]
training_y = y[0,:261].T

test_x = x[261:,:]
test_y = y[0,261:].T



classifier = tree.DecisionTreeClassifier(min_samples_split=100)
classifier.fit(training_x,training_y)

print classifier.predict(test_x)
print test_y.T[0,:]
    

error = test_y.T[0,:] - classifier.predict(test_x)
print np.sqrt(np.square(error)).sum()
#In the binary case it is performing abit better when classifiing.

[0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0]
[[0 0 1 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0]]
6.0


In [7]:
def f(x):
    if x > 0:
        return 1
    else:
        return 0

from sklearn.ensemble import RandomForestClassifier
import numpy as np

x = np.matrix(data.drop('Cases',axis=1).dropna())
y = np.matrix(data['Cases'].apply(f))

training_x = x[:261,:]
training_y = y[0,:261].T

test_x = x[261:,:]
test_y = y[0,261:].T



classifier = RandomForestClassifier(n_estimators=100)
classifier.fit(training_x,training_y)

print classifier.predict(test_x)
print test_y.T[0,:]
    

error = test_y.T[0,:] - classifier.predict(test_x)
print 1- np.sqrt(np.square(error)).sum()/len(test_x)
#Random forrest classifier has 82% accuracy on binary cases
#Next step would be to use cross validation method. 
#k-fold validation or leave one out.

/home/adam/anaconda2/envs/deeplearning/lib/python2.7/site-packages/ipykernel/__main__.py:22: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().


[0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0]
[[0 0 1 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0]]
0.827586206897


In [8]:
from sklearn.linear_model import LogisticRegression
##Regression
def f(x):
    if x > 0:
        return 1
    else:
        return 0
import numpy as np

x = np.matrix(data.drop('Cases',axis=1).dropna())
y = np.matrix(data['Cases'].apply(f))

count = 250

training_x = x[:count,:]
training_y = y[0,:count].T

test_x = x[count:,:]
test_y = y[0,count:].T



classifier = LogisticRegression()
classifier.fit(training_x,training_y)

print classifier.predict(test_x)
print test_y.T[0,:]


error = test_y.T[0,:] - classifier.predict(test_x)
print 1- np.sqrt(np.square(error)).sum()/len(test_x)
#Logistic regression has 85% accuarcy on this partition.
#Next step is to do crossvalidation aswell.
#Also needs to be compared with the base case og guessing 0 all the time.


[0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0
 0 0 0]
[[0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0
  0 0 0]]
0.85


/home/adam/anaconda2/envs/deeplearning/lib/python2.7/site-packages/sklearn/utils/validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [9]:
case_popu = np.matrix(data[['Cases','population']])



In [10]:
#Number of fire per 1000 


from sklearn.linear_model import LinearRegression
##Regression
def f(x):
    if x > 0:
        return 1
    else:
        return 0
import numpy as np

x = np.matrix(data.drop(['Cases','population'],axis=1).dropna())
# y = np.matrix((data['Cases'] / data['population']) *1e3)
y = np.matrix(data['Cases'])

count = 200

training_x = x[:count,:]
training_y = y[0,:count].T


test_x = x[count:,:]
test_y = y[0,count:].T




classifier = LinearRegression()
classifier.fit(training_x,training_y)


error = test_y[:,0] - classifier.predict(test_x)
# error = test_y[0,:] - test_y[0,:]
print ( np.sqrt(np.square(error)).sum()/len(test_y)), "Mean squared error"
print "Error" , error.shape
#This regression problem is hard to relate to.
#Option might be to 

0.850826481239 Mean squared error
Error (90, 1)


In [11]:
y = np.matrix((data['Cases'] / data['population']) *1e3)

In [12]:
test_y[:,0].shape

(90, 1)

In [ ]:
classifier.predict(test_x).shape

In [ ]:
classifier.coef_

In [ ]:
data['population']