In [1]:
import numpy as np
import pandas as pd
from pivottablejs import pivot_ui
import matplotlib.pyplot as plt
import matplotlib
from sklearn import preprocessing 
matplotlib.style.use('ggplot')
%matplotlib inline

from pylab import rcParams
rcParams['figure.figsize'] = 20, 20
rcParams.update({'font.size': 30})
rcParams.update({'figure.autolayout': True})

data = pd.read_csv("cleanSet.csv")

In [2]:
from sklearn import tree
import numpy as np

x = np.matrix(data['population'])
y = np.matrix(data['Cases'])


training_x = x[0,:261].T
traning_y = y[0,:261].T

test_x = x[0,261:].T
test_y = y[0,261:].T



classifier = tree.DecisionTreeClassifier()
classifier.fit(training_x,traning_y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [3]:
error = test_y.T -np.matrix(classifier.predict(test_x))

print np.sqrt(np.square(error)).sum()


27.0


In [4]:
from sklearn import tree
import numpy as np

x = np.matrix(data.drop('Cases',axis=1).dropna())
y = np.matrix(data['Cases'])


training_x = x[:261,:]
training_y = y[0,:261].T

test_x = x[261:,:]
test_y = y[0,261:].T



classifier = tree.DecisionTreeClassifier()
classifier.fit(training_x,training_y)

print classifier.predict(test_x)
print test_y.T[0,:]
#The tree classifier is not performing that well.

[0 5 3 0 0 0 0 0 0 0 3 0 0 0 0 0 2 0 0 0 4 0 0 0 0 0 0 1 0]
[[0 0 1 1 0 0 1 0 0 0 0 0 0 3 0 0 0 0 1 0 7 0 0 1 0 0 0 0 0]]


In [5]:
print training_x.shape
print training_y.shape

(261, 15)
(261, 1)


In [6]:
def f(x):
    if x > 0:
        return 1
    else:
        return 0

from sklearn import tree
import numpy as np

x = np.matrix(data.drop('Cases',axis=1).dropna())
y = np.matrix(data['Cases'].apply(f))

training_x = x[:261,:]
training_y = y[0,:261].T

test_x = x[261:,:]
test_y = y[0,261:].T



classifier = tree.DecisionTreeClassifier(min_samples_split=100)
classifier.fit(training_x,training_y)

print classifier.predict(test_x)
print test_y.T[0,:]
    

error = test_y.T[0,:] - classifier.predict(test_x)
print np.sqrt(np.square(error)).sum()
#In the binary case it is performing abit better when classifiing.

[0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0]
[[0 0 1 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0]]
6.0


In [7]:
def f(x):
    if x > 0:
        return 1
    else:
        return 0

from sklearn.ensemble import RandomForestClassifier
import numpy as np

x = np.matrix(data.drop('Cases',axis=1).dropna())
y = np.matrix(data['Cases'].apply(f))

training_x = x[:261,:]
training_y = y[0,:261].T

test_x = x[261:,:]
test_y = y[0,261:].T



classifier = RandomForestClassifier(n_estimators=100)
classifier.fit(training_x,training_y)

print classifier.predict(test_x)
print test_y.T[0,:]
    

error = test_y.T[0,:] - classifier.predict(test_x)
print 1- np.sqrt(np.square(error)).sum()/len(test_x)
#Random forrest classifier has 82% accuracy on binary cases
#Next step would be to use cross validation method. 
#k-fold validation or leave one out.

/home/adam/anaconda2/envs/deeplearning/lib/python2.7/site-packages/ipykernel/__main__.py:22: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().


[0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0]
[[0 0 1 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0]]
0.793103448276


In [8]:
from sklearn.linear_model import LogisticRegression
##Regression
def f(x):
    if x > 0:
        return 1
    else:
        return 0
import numpy as np

x = np.matrix(data.drop('Cases',axis=1).dropna())
y = np.matrix(data['Cases'].apply(f))

count = 250

training_x = x[:count,:]
training_y = y[0,:count].T

test_x = x[count:,:]
test_y = y[0,count:].T



classifier = LogisticRegression()
classifier.fit(training_x,training_y)

print classifier.predict(test_x)
print test_y.T[0,:]


error = test_y.T[0,:] - classifier.predict(test_x)
print 1- np.sqrt(np.square(error)).sum()/len(test_x)
#Logistic regression has 85% accuarcy on this partition.
#Next step is to do crossvalidation aswell.
#Also needs to be compared with the base case og guessing 0 all the time.


[0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0
 0 0 0]
[[0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0
  0 0 0]]
0.85


/home/adam/anaconda2/envs/deeplearning/lib/python2.7/site-packages/sklearn/utils/validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [9]:
case_popu = np.matrix(data[['Cases','population']])



In [54]:
#Number of fire per 1000 


from sklearn.linear_model import LinearRegression
##Regression
def f(x):
    if x > 0:
        return 1
    else:
        return 0
import numpy as np


x = np.matrix(data.drop(['Cases','population'],axis=1).dropna())
# y = np.matrix((data['Cases'] / data['population']) *1e3)
y = np.matrix(data['Cases'])

count = 200

training_x = x[:count,:]
training_y = y[0,:count].T


test_x = x[count:,:]
test_y = y[0,count:].T




classifier = LinearRegression()
classifier.fit(training_x,training_y)


error = test_y[:,0] - classifier.predict(test_x)
# error = test_y[0,:] - test_y[0,:]
print ( np.sqrt(np.square(error)).sum()/len(test_y)), "Mean squared error"
print "Error" , error.shape
#This regression problem is hard to relate to.
#Option might be to 

0.850826481239 Mean squared error
Error (90, 1)


In [55]:
y = np.matrix((data['Cases'] / data['population']) *1e3)

In [57]:
#Number of fire per 1000 
#Regression on reported crime


from sklearn.linear_model import LinearRegression
##Regression
def f(x):
    if x > 0:
        return 1
    else:
        return 0
import numpy as np

data_normalized =  (data - data.mean()) / (data.max() - data.min())
x = np.matrix(data_normalized.drop(['reportedCrime','reportedCrimeVandalism','youngUnskilled'],axis=1).dropna())
# y = np.matrix((data['Cases'] / data['population']) *1e3)
y = np.matrix(data['reportedCrime'])

count = 200

training_x = x[:count,:]
training_y = y[0,:count].T


test_x = x[count:,:]
test_y = y[0,count:].T


classifier = LinearRegression()
classifier.fit(training_x,training_y)


error = test_y[:,0] - classifier.predict(test_x)
# error = test_y[0,:] - test_y[0,:]
mean_square_error = np.sqrt(np.square(error)).sum()/len(test_y)
print (mean_square_error), "Mean squared error"
print "Error" , error.shape
#This regression problem is hard to relate to.
#Option might be to 

169.723486779 Mean squared error
Error (90, 1)


In [58]:
np.sqrt(mean_square_error)


13.027796697035818

In [59]:
-9.73057296e+01

-97.3057296

In [60]:
np.argmax(classifier.coef_)

10

In [61]:
classifier.coef_[0]

array([ -292.86988346,  -792.08175812,  -140.70126931,    -5.90238613,
          98.43523667,   467.89201511,  -468.38057726,   331.99687854,
         458.73526159,   527.23369936,  1130.83335682,     2.817745  ,
         -99.3090168 ])

In [62]:
data_normalized.drop(['reportedCrime','reportedCrimeVandalism'],axis=1).dropna()


Cases  medianIncome  youthUnemployment2013  unemployment2013  \
0    0.017241      0.148607              -0.141760         -0.172633   
1   -0.030378      0.065401              -0.062813         -0.099906   
2    0.017241      0.006173               0.163503          0.136458   
3   -0.030378     -0.039517               0.026661         -0.072633   
4   -0.030378     -0.061013               0.063503          0.136458   
5   -0.030378     -0.080973              -0.036497         -0.118088   
6   -0.030378     -0.051750               0.095082         -0.018088   
7   -0.030378     -0.088098               0.116134          0.072821   
8   -0.030378     -0.041562              -0.036497         -0.118088   
9   -0.030378     -0.010530               0.068766          0.000094   
10   0.017241     -0.191214               0.226661          0.081912   
11  -0.030378     -0.194170               0.016134         -0.018088   
12  -0.030378     -0.206820               0.079292          0.254639   
13  -0.030378     -0.050401              -0.036497          0.154639   
14  -0.030378     -0.005601               0.247713          0.109185   
15  -0.030378      0.162254              -0.083866         -0.227179   
16  -0.030378     -0.096471               0.195082          0.254639   
17  -0.030378     -0.166361              -0.015445         -0.090815   
18   0.160099     -0.010466              -0.110181          0.000094   
19   0.255337      0.017100              -0.110181         -0.018088   
20   0.160099     -0.039617              -0.152287          0.200094   
21  -0.030378     -0.024500               0.089819          0.036458   
22  -0.030378     -0.053034               0.537187          0.363730   
23  -0.030378     -0.162020               0.142450          0.300094   
24   0.017241     -0.032421               0.021397          0.136458   
25   0.017241      0.027525              -0.078603         -0.136270   
26  -0.030378     -0.223810               0.131924          0.036458   
27  -0.030378      0.763850              -0.462813         -0.481724   
28   0.017241     -0.108115               0.000345          0.081912   
29  -0.030378     -0.171491              -0.125971          0.172821   
..        ...           ...                    ...               ...   
260 -0.030378      0.093182              -0.331234         -0.345361   
261 -0.030378     -0.079516              -0.036497         -0.081724   
262 -0.030378      0.085368               0.184555          0.163730   
263  0.017241      0.063105               0.000345          0.091003   
264  0.017241      0.029928              -0.068076          0.054639   
265 -0.030378     -0.066752              -0.115445         -0.272633   
266 -0.030378      0.025781               0.147713         -0.045361   
267  0.017241      0.077677               0.284555          0.263730   
268 -0.030378     -0.167832               0.163503          0.227367   
269 -0.030378     -0.062656              -0.247024         -0.254451   
270 -0.030378     -0.106157              -0.236497         -0.190815   
271 -0.030378      0.083403               0.047713          0.345549   
272 -0.030378     -0.156345              -0.041760          0.136458   
273 -0.030378     -0.110813               0.026661          0.018276   
274  0.112479     -0.060898               0.021397         -0.099906   
275 -0.030378     -0.188725               0.110871          0.063730   
276 -0.030378     -0.218220               0.289819          0.291003   
277 -0.030378     -0.053945               0.031924          0.127367   
278 -0.030378     -0.048779              -0.031234         -0.090815   
279  0.017241      0.192195              -0.241760         -0.354451   
280 -0.030378     -0.121841              -0.052287          0.036458   
281  0.302956      0.019554              -0.078603          0.036458   
282 -0.030378     -0.101027              -0.052287         -0.054451   
283 -0.030378      0.004608               0.1056

In [69]:
data

Cases  medianIncome  youthUnemployment2013  unemployment2013  \
0        1        218334                    7.3               5.5   
1        0        206737                    8.8               6.3   
2        1        198482                   13.1               8.9   
3        0        192114                   10.5               6.6   
4        0        189118                   11.2               8.9   
5        0        186336                    9.3               6.1   
6        0        190409                   11.8               7.2   
7        0        185343                   12.2               8.2   
8        0        191829                    9.3               6.1   
9        0        196154                   11.3               7.4   
10       1        170971                   14.3               8.3   
11       0        170559                   10.3               7.2   
12       0        168796                   11.5              10.2   
13       0        190597                    9.3               9.1   
14       0        196841                   14.7               8.6   
15       0        220236                    8.4               4.9   
16       0        184176                   13.7              10.2   
17       0        174435                    9.7               6.4   
18       4        196163                    7.9               7.4   
19       6        200005                    7.9               7.2   
20       4        192100                    7.1               9.6   
21       0        194207                   11.7               7.8   
22       0        190230                   20.2              11.4   
23       0        175040                   12.7              10.7   
24       1        193103                   10.4               8.9   
25       1        201458                    8.5               5.9   
26       0        166428                   12.5               7.8   
27       0        304084                    1.2               2.1   
28       1        182553                   10.0               8.3   
29       0        173720                    7.6               9.3   
..     ...           ...                    ...               ...   
260      0        210609                    3.7               3.6   
261      0        186539                    9.3               6.5   
262      0        209520                   13.5               9.2   
263      1        206417                   10.0               8.4   
264      1        201793                    8.7               8.0   
265      0        188318                    7.8               4.4   
266      0        201215                   12.8               6.9   
267      1        208448                   15.4              10.3   
268      0        174230                   13.1               9.9   
269      0        188889                    5.3               4.6   
270      0        182826                    5.5               5.3   
271      0        209246                   10.9              11.2   
272      0        175831                    9.2               8.9   
273      0        182177                   10.5               7.6   
274      3        189134                   10.4               6.3   
275      0        171318                   12.1               8.1   
276      0        167207                   15.5              10.6   
277      0        190103                   10.6               8.8   
278      0        190823                    9.4               6.4   
279      1        224409                    5.4               3.5   
280      0        180640                    9.0               7.8   
281      7        200347                    8.5               7.8   
282      0        183541                    9.0               6.8   
283      0        198264                   12.0               8.7   
284      1        196228                   10.3               7.0   
285      0        241201                    4.2               3.5   
286